### ISSUE TITLE
Problem since updating to ver. 0.12.8.6-unstable

### ISSUE THREAD

**Issue by KevM3333** [zer0fixer/MAS-Extraplus#4]
Hey I want to report about the an error i encounter when trying playing with Monika or asking her to flip a coin through Extra+ option after I update the mod to version 0.12.8.6 that include UNO (or NOU for some reason) and I think it has to do with the definiton.rpy on the mod folder here's one of many error message I got when I try to do anything beside touching her cheeks, head, and nose.
![Error SS](https://user-images.githubusercontent.com/97391028/177104764-6e5521c6-f229-48bf-bf6f-56e1bb8845f0.PNG)

**Comment by zer0fixer** [comment]
> Hey I want to report about the an error i encounter when trying playing with Monika or asking her to flip a coin through Extra+ option after I update the mod to version 0.12.8.6 that include UNO (or NOU for some reason) and I think it has to do with the definiton.rpy on the mod folder here's one of many error message I got when I try to do anything beside touching her cheeks, head, and nose. ![Error SS](https://user-images.githubusercontent.com/97391028/177104764-6e5521c6-f229-48bf-bf6f-56e1bb8845f0.PNG)



> Hey I want to report about the an error i encounter when trying playing with Monika or asking her to flip a coin through Extra+ option after I update the mod to version 0.12.8.6 that include UNO (or NOU for some reason) and I think it has to do with the definiton.rpy on the mod folder here's one of many error message I got when I try to do anything beside touching her cheeks, head, and nose. ![Error SS](https://user-images.githubusercontent.com/97391028/177104764-6e5521c6-f229-48bf-bf6f-56e1bb8845f0.PNG)

It is because the coin sprite (sprite_coin.png) is not in your MAS. If you have not extracted the submod and you just copy directly from the zip file without extracting the contents, that causes the files to not copy correctly. I suggest you extract the submod with winrar or 7zip to resolve the issue. But if the error persists, you can talk to me on discord or reddit to help you better.
![Screenshot (6)](https://user-images.githubusercontent.com/94260040/177187767-e2675c2b-6809-4d5e-83a5-ca332f6b16fc.png)

**Comment by zer0fixer** [comment]
Although you probably downloaded it from Google Drive and didn't see the reddit post, an apology in advance. I'll put a note to avoid this.

**Comment by zer0fixer** [comment]
About the submod update: I see that many people are having problems with it. That's why I haven't uploaded more updates for now. I will see how I can fix it. So sorry for the inconvenience.

**Comment by KevM3333** [comment]
I found what is the real problem, it turns out I extracted the entire MAS-Extraplus-1.0.2.zip file into the submod folder to isntall the mod that causing the mod to not able to find all the submod assets after that I fix it by cutting the "ExtraPlus" folder and put it in submod folder. so in short the submod is working as it should be (sorry for bad englsih spelling I am for indonesia)
