### ISSUE TITLE
Shell game automatically chooses a cup

### ISSUE THREAD

**Issue by d3adpan** [zer0fixer/MAS-Extraplus#6]
The shell game will automatically select the middle cup for the player and cycle through the game endlessly, if the text box dialogue option is set to 'Auto'.  The "Turn" count increases each time, rather than the "Reply" count.

Turning 'Auto' off with either the button or by clicking somewhere on the MAS screen makes the shell game work normally.

**Comment by zer0fixer** [comment]
> The shell game will automatically select the middle cup for the player and cycle through the game endlessly, if the text box dialogue option is set to 'Auto'. The "Turn" count increases each time, rather than the "Reply" count.
> 
> Turning 'Auto' off with either the button or by clicking somewhere on the MAS screen makes the shell game work normally.

Thanks for reporting it. It has been fixed.

**Comment by d3adpan** [comment]
Awesome, thanks!
