### ISSUE TITLE
issue about boop in restaurant 

### ISSUE THREAD

**Issue by wowm03** [zer0fixer/MAS-Extraplus#9]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Submods/ExtraPlus/Extra_Plus_Labels.rpy", line 266, in script
    call screen dating_loop(extraplus_acs_pudding, extraplus_acs_icecream, "restaurant_talk","monika_no_food", "monika_booprestaurant", boop_enable=True)
ScriptError: could not find label 'monika_booprestaurant'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\hilla\OneDrive\桌面\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\hilla\OneDrive\桌面\DDLC-1.1.1-pc\renpy\main.py", line 487, in main
    run(restart)
  File "C:\Users\hilla\OneDrive\桌面\DDLC-1.1.1-pc\renpy\main.py", line 147, in run
    renpy.execution.run_context(True)
  File "C:\Users\hilla\OneDrive\桌面\DDLC-1.1.1-pc\renpy\execution.py", line 761, in run_context
    context.run()
  File "game/Submods/ExtraPlus/Extra_Plus_Labels.rpy", line 266, in script
    call screen dating_loop(extraplus_acs_pudding, extraplus_acs_icecream, "restaurant_talk","monika_no_food", "monika_booprestaurant", boop_enable=True)
  File "C:\Users\hilla\OneDrive\桌面\DDLC-1.1.1-pc\renpy\script.py", line 858, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'monika_booprestaurant'.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.11

**Comment by zer0fixer** [comment]
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code: File "game/Submods/ExtraPlus/Extra_Plus_Labels.rpy", line 266, in script call screen dating_loop(extraplus_acs_pudding, extraplus_acs_icecream, "restaurant_talk","monika_no_food", "monika_booprestaurant", boop_enable=True) ScriptError: could not find label 'monika_booprestaurant'.
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback: File "C:\Users\hilla\OneDrive\桌面\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap renpy.main.main() File "C:\Users\hilla\OneDrive\桌面\DDLC-1.1.1-pc\renpy\main.py", line 487, in main run(restart) File "C:\Users\hilla\OneDrive\桌面\DDLC-1.1.1-pc\renpy\main.py", line 147, in run renpy.execution.run_context(True) File "C:\Users\hilla\OneDrive\桌面\DDLC-1.1.1-pc\renpy\execution.py", line 761, in run_context context.run() File "game/Submods/ExtraPlus/Extra_Plus_Labels.rpy", line 266, in script call screen dating_loop(extraplus_acs_pudding, extraplus_acs_icecream, "restaurant_talk","monika_no_food", "monika_booprestaurant", boop_enable=True) File "C:\Users\hilla\OneDrive\桌面\DDLC-1.1.1-pc\renpy\script.py", line 858, in lookup raise ScriptError("could not find label '%s'." % str(original)) ScriptError: could not find label 'monika_booprestaurant'.
> 
> Windows-8-6.2.9200 Ren'Py 6.99.12.4.2187 Monika After Story 0.12.11

Thanks for reporting. Until today I see the bugs an apology.
